#!/usr/bin/python

# CMSC 12300 - Computer Science with Applications 3
# Borja Sotomayor, 2013

"""
Solves a system of linear equations.

Despite its name, this Python program does
*not* use the Jacobi method. It uses
numpy's np.linalg.solve function.

The command takes a single parameter:

    jacobi_np_linalg.py FILE

FILE: A file containing the system of linear
equations (as generated by gen_lineq.py)
"""

import sys
import numpy as np

fname = sys.argv[1]
f = open(fname)

numEq, numVar = f.readline().strip().split()

numEq = int(numEq)
numVar = int(numVar)

assert(numEq == numVar)

N = numEq

A = np.empty((N,N))
b = np.empty((N,))

for i, line in enumerate(f):
    nums = [float(x) for x in line.strip().split()]
    for j in range(N):
        A[i,j] = nums[j]
    b[i] = nums[-1]

solution = np.linalg.solve(A, b)
b_sol = np.dot(A, solution)

for i in range(N):
    print "x_%i = %.3f" % (i, solution[i])

print

for i in range(N):
    print "b_%i = %.3f (%.3f)" % (i, b_sol[i], b[i])

